<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="bracelet_board" params="name parent pos">
    <xacro:property name="pos_z" value="${(0.02 + 0.005)*pos}" />
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" />
        <geometry>
          <box size="0.02 0.005 0.04" />
        </geometry>
      </visual>
    </link>
    <joint name="${name}_joint" type="fixed" >
      <parent link="${parent}" />
      <child link="${name}_link" />
      <origin xyz="0.0 0.0 ${pos_z + 0.01}" rpy="${pi} ${90/180.0*pi} 0.0" />
    </joint>
    <sensor name="${name}_sensor" update_rate="100">
      <xacro:property name="cell_size" value="0.005" />
      <xacro:property name="cell_spacing" value="0.005" />
      <xacro:property name="bracelet_size_x" value="4" />
      <xacro:property name="bracelet_size_y" value="8" />
      <parent link="${name}_link"/>
      <origin xyz="0 -0.0026 0" rpy="${pi/2.0} ${pi/2.0} 0.0" />
      <tactile channel="${name}">
        <array rows="${bracelet_size_y}" cols="${bracelet_size_x}"
            order="row-major" size="${cell_size} ${cell_size}" 
            offset="${cell_spacing * (bracelet_size_y -1.0)/2.0} ${cell_spacing * (bracelet_size_x -1.0)/2.0}">
        </array>
      </tactile>
    </sensor>
  </xacro:macro>

  <xacro:macro name="bracelet" >
    <link name="bracelet_base" />
    <xacro:bracelet_board name="board0" parent="bracelet_base" pos="8"/>
    <xacro:bracelet_board name="board1" parent="bracelet_base" pos="7"/>
    <xacro:bracelet_board name="board2" parent="bracelet_base" pos="6"/>
    <xacro:bracelet_board name="board3" parent="bracelet_base" pos="5"/>
    <xacro:bracelet_board name="board4" parent="bracelet_base" pos="4"/>
    <xacro:bracelet_board name="board5" parent="bracelet_base" pos="3"/>
    <xacro:bracelet_board name="board6" parent="bracelet_base" pos="2"/>
    <xacro:bracelet_board name="board7" parent="bracelet_base" pos="1"/>
    <xacro:bracelet_board name="board8" parent="bracelet_base" pos="0"/>
  </xacro:macro>  
</robot>

