position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - thumb_abduction_joint
    - thumb_proximal_joint
    - thumb_middle_joint
    - thumb_distal_joint
    - index_abduction_joint
    - index_proximal_joint
    - index_middle_joint
    - index_distal_joint
    - middle_abduction_joint
    - middle_proximal_joint
    - middle_middle_joint
    - middle_distal_joint
    - ring_abduction_joint
    - ring_proximal_joint
    - ring_middle_joint
    - ring_distal_joint
    - little_abduction_joint
    - little_proximal_joint
    - little_middle_joint
    - little_distal_joint
  gains:
    thumb_abduction_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    thumb_proximal_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    thumb_middle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    thumb_distal_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    index_abduction_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    index_proximal_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    index_middle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    index_distal_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    middle_abduction_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    middle_proximal_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    middle_middle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    middle_distal_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ring_abduction_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ring_proximal_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ring_middle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ring_distal_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    little_abduction_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    little_proximal_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    little_middle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    little_distal_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1