# Goal sends desired pose or linear combination of poses
uint8 repeats
float32 hold_secs
float32 period_seconds
string[] gesture_name
float32[] gesture_weight
string[] start_gesture_name
float32[] start_gesture_weight
---
# Result
uint8 return_state
uint8 SUCCESS=0
uint8 TARGET_GESTURE_UNKNOWN=1
---
# Feedback
float32 seconds_left
uint8 repeat_counter
