gestures:
  fist:
    joint: [thumb_abduction_joint, thumb_proximal_joint, thumb_middle_joint, thumb_distal_joint,
      index_abduction_joint, index_proximal_joint, index_middle_joint, index_distal_joint,
      middle_abduction_joint, middle_proximal_joint, middle_middle_joint, middle_distal_joint,
      ring_abduction_joint, ring_proximal_joint, ring_middle_joint, ring_distal_joint,
      little_abduction_joint, little_proximal_joint, little_middle_joint, little_distal_joint]
    position: [0.6800040130544744, 0.1560562414195817, 0.7717071026156601,
      0.7005751617532786, 0.004049163864628447, 1.332349444383278, 2.18166156499, 1.155163618721366,
      0.0013264502315162296, 1.23464591285694, 2.18166156499, 1.497440138328907, -0.004049163864628447,
      1.301875995643552, 2.18166156499, 1.2591503355548639, 0.0013264502315162296, 1.381358289779126,
      1.748819910495984, 1.57079632679]

  neutral:
    joint: [distal_radioulnar_joint, index_abduction_joint, index_distal_joint, index_middle_joint, index_proximal_joint, little_abduction_joint, little_distal_joint, little_middle_joint, little_proximal_joint, middle_abduction_joint, middle_distal_joint, middle_middle_joint, middle_proximal_joint, radiocarpal_abductor_joint, radiocarpal_flexor_joint, ring_abduction_joint, ring_distal_joint, ring_middle_joint, ring_proximal_joint, thumb_abduction_joint, thumb_distal_joint, thumb_middle_joint, thumb_proximal_joint]
    position: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

  index_flexion:
    joint: [index_proximal_joint, index_middle_joint, index_distal_joint]
    position: [0.12, 1.97, 0.55]

  middle_flexion:
    joint: [middle_proximal_joint, middle_middle_joint, middle_distal_joint]
    position: [0.12, 1.97, 0.55]

  ring_flexion:
    joint: [ring_proximal_joint, ring_middle_joint, ring_distal_joint]
    position: [0.22, 2.07, 0.55]

  little_flexion:
    joint: [little_proximal_joint, little_middle_joint, little_distal_joint]
    position: [0.08, 1.81, 0.47]

  thumb_flexion_a:
    joint: [thumb_abduction_joint, thumb_middle_joint, thumb_distal_joint]
    position: [0.13, 0.93, 1.54]
    
  thumb_flexion_b:
    joint: [thumb_abduction_joint, thumb_middle_joint]
    position: [0.91, 1.05]

  fist_index:
    joint: [index_proximal_joint, index_middle_joint, index_distal_joint]
    position: [0.74, 1.98, 1.22]

  fist_middle:
    joint: [middle_proximal_joint, middle_middle_joint, middle_distal_joint]
    position: [0.65, 2.02, 1.20]

  fist_ring:
    joint: [ring_proximal_joint, ring_middle_joint, ring_distal_joint]
    position: [0.58, 2.16, 1.21]

  fist_little:
    joint: [little_proximal_joint, little_middle_joint, little_distal_joint]
    position: [0.46, 2.12, 1.18]

  fist_thumb:
    joint: [thumb_abduction_joint, thumb_proximal_joint, thumb_middle_joint]
    position: [0.48, 0.35, 0.69]

  palmar_flexion:
    joint: [radiocarpal_flexor_joint]
    position: [-1.05]

  dorsal_extension:
    joint: [radiocarpal_flexor_joint]
    position: [1.05]

  pronation:
    joint: [distal_radioulnar_joint]
    position: [3.05]

  supination:
    joint: [distal_radioulnar_joint]
    position: [-0.17]
