rec_steps:
  - gesture:
      description: Pronated Fist Palmar Extension
      wait_seconds: 3
      gesture_name:
        - palmar_extension
      start_gesture_name:
        - fist
        - pronation
      repeats: 2
      period_seconds: 4
      familiarization_repeats: 1
