rec_steps:
  - gesture:
      description: Pronated Fist Palmar Flexion
      wait_seconds: 3
      gesture_name:
        - palmar_flexion
      gesture_weight:
        - 0.85
      start_gesture_name:
        - fist
        - pronation
      repeats: 10
      period_seconds: 4
      familiarization_repeats: 2
