rec_steps:
  - gesture:
      description: Pronated Palmar Extension
      wait_seconds: 3
      gesture_name:
        - palmar_extension
      start_gesture_name:
        - neutral
        - pronation
      repeats: 10
      period_seconds: 4
      familiarization_repeats: 1
