rec_steps:
  - gesture:
      description: Supinated Fist Palmar Extension
      wait_seconds: 3
      gesture_name:
        - palmar_flexion
      gesture_weight:
        - 0.6
      start_gesture_name:
        - fist
        - supination
      repeats: 10
      period_seconds: 4
      familiarization_repeats: 2
